name: Deploy

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string

jobs:
  deploy-staging:
    name: Deploy staging
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/my-action@v1
        with:
          stage: ${{ inputs.stage }}
      - name: Deploy to production
        run: echo stage is ${{ inputs.stage }}
