name: Deploy

on:
  workflow_call:
    inputs:
      production:
        required: true
        type: boolean

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        if: ${{ inputs.production == false }}
        run: echo production is false

      - name: Deploy to production
        if: ${{ inputs.production }}
        run: echo production is true

      - name: Check secrets
        if: ${{ secrets.FOO == "BAR" }}
        run: secrets.FOO is "BAR"
