name: Deploy

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        if: ${{ inputs.stage == "staging" }}
        run: echo stage is ${{ inputs.stage }}

      - name: Deploy to production
        if: ${{ inputs.stage == "production" }}
        run: echo stage is ${{ inputs.stage }}

      - name: Check secrets
        if: ${{ secrets.FOO == "BAR" }}
        run: secrets.FOO is "BAR"
