name: Deploy

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: echo stage is ${{ inputs.stage }}
